### ISSUE TITLE
CSS issue 

### ISSUE THREAD

**Issue by parthpathakpp1** [parthpathakpp1/AppleDoors#9]
On every page, there is an extra space that I want to be removed. This includes the customization page. Additionally, when we attempt to rotate the 3D model, it shifts, and this extra space becomes visible.

https://github.com/parthpathakpp1/AppleDoors/assets/85991449/ff7fdb88-ac35-4a13-971e-b214efc02597

**Comment by IrfanshaikH-7** [comment]
Where is the code?

**Comment by parthpathakpp1** [comment]
> Where is the code?

check the master branch. The code is there and make sure to clone master branch

**Comment by danishhansari** [comment]
can i statt working on this

**Comment by parthpathakpp1** [comment]
> can i statt working on this

@danishhansari yes you can start working on it
